[tool.poetry]
name = "camphr_cli"
version = "0.1.0"
description = ""
authors = ["Yohei Tamura <tamuhey@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.4.0"
hydra-core = "0.11.3"
scikit-learn = ">=0.22,<0.25"

# TODO
camphr = {path = "../..", develop=true}
camphr_core = {path = "../camphr_core", develop=true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.812"
flake8 = "^3.9.2"

[tool.poetry.scripts]
camphr = "camphr_cli.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
