version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    machine: 
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: login
          command: echo "$dockerhub_password" | docker login --username $dockerhub_username --password-stdin
      - run: docker-compose build
      - run:
          name: run pytest
          command: docker-compose run -e CI ner pipenv run pytest -v
      # - run:
      #     name: run train script test
      #     command: docker-compose run -e CI ner pipenv run python scripts/test_train.py matrix
      - run: docker-compose run -e CI ner sh -c "pwd && ls ."
