model:
    lang:
        name:
        optimizer:
            class: transformers.optimization.AdamW
train:
    data:
        path: foo
        ndata: -1
        val_size: 0.1
    niter: 10
    nbatch: 16

