# Automatically update CHANGELOG.md and create release when tag is pushed
name: Release Notes

on: 
  push:
    tags:

jobs:
  release:
    if: contains(github.event.head_commit.message, '[versionup]') == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    - run: npm install github-release-notes -g
    - run: gren changelog --override --token ${{secrets.GITHUB_TOKEN}} 
    - run: gren release --override --token ${{secrets.GITHUB_TOKEN}}
    - name: commit
      run: |
        git add .
        git commit -m "Update Changelog"
        git push github HEAD:${GITHUB_REF}